language: php

php:
  - 5.3
  - 5.6

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --dev

script: 
 - mkdir -p build/logs
 - vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml

after_script:
 - vendor/bin/coveralls -v
